version: '3'

services:
  khan:
    image: mysql:5.7
    container_name: khan_db
    env_file:
      - .env
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: khan_pma
    links:
      - khan
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80

volumes:
  dbdata:
